---
- name: Backup Check
  hosts: 192.168.0.111
  become: yes
  tasks:
    - name: Get current date
      command: date +"%Y%m%d"
      register: current_date_raw
      changed_when: false
      check_mode: no

    - name: Format current date
      set_fact:
        current_date: "{{ current_date_raw.stdout.strip() }}"

    - name: Check if backup files exist
      command: find /home/master/backup -maxdepth 1 -type f -name "backup_{{ current_date }}*.dump"
      register: backup_files
      ignore_errors: true

    - name: Display status of backup files
      debug:
        msg: "Backup for the current date {{ current_date }} exists."
      when: backup_files.stdout_lines | length > 0
